### ISSUE TITLE
Error after editing png files and trying to compress again

### ISSUE THREAD

**Issue by esad65** [MasterDevX/XCoder#1]
Is there something I have to consider?

**Comment by MasterDevX** [comment]
> Is there something I have to consider?

Please tell me more info about your problem: where have you placed your png files, which error message do you get when trying to compress, etc. Including screenshots can help to solve problem faster.
P.S. XCoder may not work if you downloaded it directly. Try redownloading it from releases page: https://github.com/MasterDevX/XCoder/releases

**Comment by esad65** [comment]
Anyways I tried again and it worked. Also do you know why the game uses the original csv Files after I edit them? I wanted to add some mods for private game.

**Comment by MasterDevX** [comment]
>  wanted to add some mods for private game.

You can't edit CSV's, which include game logic.
