### ISSUE TITLE
Doesn't work with newest BS update

### ISSUE THREAD

**Issue by ElDavoo** [MasterDevX/XCoder#10]
Trying to decompile loading_tex.sc from latest Brawl Stars update.

Traceback (most recent call last):
  File "./SC-Decode.py", line 175, in <module>
    decompileSC(folder + file)
  File "./SC-Decode.py", line 76, in decompileSC
    if data[0] != 93:
IndexError: index out of range

With Python 3.7

**Comment by MasterDevX** [comment]
Looks like your loading_tex.sc is corrupted, I've just checked and the newest loading screen decompiles just fine. You can see that script fails when checking the first byte of a file (data[0]) and says "index out of range", what means this byte is unavailable. So yeah, most likely you're trying to decompile damaged file and it even has 0 bytes size. You can see decompilation succeeded on my screenshot.
![Знімок екрана з 2020-01-24 18-50-20](https://user-images.githubusercontent.com/32103950/73087746-a548e800-3edb-11ea-8df0-9f1608fa8304.png)

**Comment by ElDavoo** [comment]
Yes, you're right. I feel so noob because I didn't check such a basic
thing. Sorry for the problem :)

Il ven 24 gen 2020, 18:00 MasterDevX <notifications@github.com> ha scritto:

**Comment by MasterDevX** [comment]
@ElDavoo No problem, feel free to report any troubles you're facing ✌
