### ISSUE TITLE
decrypt .sc files

### ISSUE THREAD

**Issue by CentaxYT** [MasterDevX/XCoder#11]
Hello,
your program to get png from a _tex.sc file is very good and works well. But i would ask if you if its also possible to decrypt only .sc files? Not textures. The normal .sc files. I dont know where i can otherwise contact you, so i made here an issue.

Thanks

**Comment by MasterDevX** [comment]
Hey, currently you are unable to decrypt .sc with XCoder.
Take a look at [this](https://github.com/clanner/cocdp), it might be you'll find something useful for you there.

**Comment by nezostore** [comment]
const _0x2d4fc1=_0x39cb;function _0x26eb(){const _0x1e0bae=['WebMessageInfo','awesome-phonenumber','./lib/exif','audio','./lib/mongoDB','suara','3194005MBdsVZ','string','.\x20Maaf\x20@','\x0aitem1.TEL;waid=','Device\x20Logged\x20Out,\x20Please\x20Delete\x20Folder\x20Session\x20yusril\x20and\x20Scan\x20Again.','3993354LHYimk','726938CQEuuR','creds','sendFile','test','*\x20tidak\x20bisa\x20menerima\x20panggilan\x20','467606XhYIQL','sendImage','join','axios','restartRequired','Connection\x20closed,\x20reconnecting....','startsWith','endsWith','sendTextWithMentions','requestPairingCode','6LHDuLk','pino','@g.us','matchAll','./lib/sticker.js','timedOut','categories','Connection\x20Replaced,\x20Another\x20New\x20Session\x20Opened,\x20Please\x20Restart\x20Bot','Pairing\x20code:\x20','store','includes','question','asSticker','exitProcess','notify','.bin','writeFile','isBuffer','lowdb','base64','ignore','packname','document','./setting','status','./lib/lowdb','decodeJid','readViewOnce','withoutContact','READ','authState','sendMessage','conversation','Update\x20','data','createInterface','readline','WhatsApp','open','isGroup','\x0aFN:','ephemeralMessage','unlink','updateBlockStatus','offer','split','remoteJid','chain','map','chalk','2360073lmAFyf','video','contacts.update','image/webp','server','groupMetadata','Connection\x20Lost\x20from\x20Server,\x20reconnecting...','getFile','asDocument','call','mtype','length','promises','participant','readFileSync','connectionReplaced','log','push','sendContact','packname2','@broadcast','Bad\x20Session\x20File,\x20Please\x20Delete\x20Session\x20and\x20Scan\x20Again','verifiedName','writeFileSync','text','error','./rikishop','key','Restart\x20Required,\x20Restarting...','@hapi/boom','sendImageAsSticker','getNumber','./src/database.json','4hWAuzs','author','sticker','relayMessage','sendVideoAsSticker','unwatchFile','name','lodash','5140499rrfPAB','\x0aitem1.X-ABLabel:Ponsel\x0aitem2.EMAIL;type=INTERNET:aplusscell@gmail.com\x0aitem2.X-ABLabel:Email\x0aitem3.URL:https://chat.whatsapp.com/HbCl8qf3KQK1MEp3ZBBpSf\x0aitem3.X-ABLabel:Instagram\x0aitem4.ADR:;;Indonesia;;;;\x0aitem4.X-ABLabel:Region\x0aEND:VCARD','fromObject','public','replace','keys','msg','type','international','anticall','ext','BAE5','getName','slice','redBright','badSession','sessionName','concat','connection.update','alloc','DATABASE','contextInfo','file-type','message','existsSync','status@broadcast','connectionClosed','0@s.whatsapp.net','mimetype','\x20Kontak','cache','./lib/myfunc','fromBuffer','subject','from','exit','fromMe','watchFile','connectionLost','sendText','loadDatabase','messages.upsert','silent','@s.whatsapp.net','parse','registered','3002488iBflAH','close','viewOnceMessage','messages','contacts','user','BEGIN:VCARD\x0aVERSION:3.0\x0aN:','../src/','Connection\x20TimedOut,\x20Reconnecting...','caption','viewOnce','block','copyNForward','argv'];_0x26eb=function(){return _0x1e0bae;};return _0x26eb();}(function(_0xb3f5be,_0x5d4902){const _0x55d9e5=_0x39cb,_0x3343dd=_0xb3f5be();while(!![]){try{const _0x512059=-parseInt(_0x55d9e5(0x1f7))/0x1+parseInt(_0x55d9e5(0x1f2))/0x2+parseInt(_0x55d9e5(0x181))/0x3*(-parseInt(_0x55d9e5(0x1a2))/0x4)+-parseInt(_0x55d9e5(0x1ec))/0x5*(-parseInt(_0x55d9e5(0x201))/0x6)+parseInt(_0x55d9e5(0x1aa))/0x7+parseInt(_0x55d9e5(0x1d8))/0x8+-parseInt(_0x55d9e5(0x1f1))/0x9;if(_0x512059===_0x5d4902)break;else _0x3343dd['push'](_0x3343dd['shift']());}catch(_0x4e7eba){_0x3343dd['push'](_0x3343dd['shift']());}}}(_0x26eb,0x650ef),require(_0x2d4fc1(0x218)));function _0x39cb(_0xa123b5,_0x709769){const _0x26ebcf=_0x26eb();return _0x39cb=function(_0x39cb89,_0x53e563){_0x39cb89=_0x39cb89-0x175;let _0x41ca47=_0x26ebcf[_0x39cb89];return _0x41ca47;},_0x39cb(_0xa123b5,_0x709769);}const {default:makeWASocket,useMultiFileAuthState,DisconnectReason,fetchLatestBaileysVersion,generateForwardMessageContent,prepareWAMessageMedia,generateWAMessageFromContent,generateMessageID,downloadContentFromMessage,makeInMemoryStore,jidDecode,getAggregateVotesInPollMessage,proto}=require('@whiskeysockets/baileys'),fs=require('fs'),pino=require(_0x2d4fc1(0x202)),chalk=require(_0x2d4fc1(0x180)),path=require('path'),readline=require(_0x2d4fc1(0x225)),axios=require(_0x2d4fc1(0x1fa)),FileType=require(_0x2d4fc1(0x1c0)),yargs=require('yargs/yargs'),_=require(_0x2d4fc1(0x1a9)),{Boom}=require(_0x2d4fc1(0x19e)),PhoneNumber=require(_0x2d4fc1(0x1e7)),usePairingCode=!![],{imageToWebp,videoToWebp,writeExifImg,writeExifVid}=require(_0x2d4fc1(0x1e8)),{smsg,isUrl,generateMessageTag,getBuffer,getSizeMedia,fetchJson,await,sleep}=require(_0x2d4fc1(0x1c9)),question=_0x2fd34f=>{const _0x15dd94=_0x2d4fc1,_0x2334a9=readline[_0x15dd94(0x224)]({'input':process['stdin'],'output':process['stdout']});return new Promise(_0x6c0aa5=>{const _0x27ea15=_0x15dd94;_0x2334a9[_0x27ea15(0x20c)](_0x2fd34f,_0x6c0aa5);});};var low;try{low=require(_0x2d4fc1(0x213));}catch(_0x2b45af){low=require(_0x2d4fc1(0x21a));}const {Low,JSONFile}=low,mongoDB=require(_0x2d4fc1(0x1ea)),store=makeInMemoryStore({'logger':pino()['child']({'level':_0x2d4fc1(0x1d4),'stream':_0x2d4fc1(0x20a)})});global['opts']=new Object(yargs(process[_0x2d4fc1(0x1e5)][_0x2d4fc1(0x1b7)](0x2))[_0x2d4fc1(0x20e)](![])[_0x2d4fc1(0x1d6)]()),global['db']=new Low(/https?:\/\//[_0x2d4fc1(0x1f5)](opts['db']||'')?new cloudDBAdapter(opts['db']):/mongodb/[_0x2d4fc1(0x1f5)](opts['db'])?new mongoDB(opts['db']):new JSONFile(_0x2d4fc1(0x1a1))),global[_0x2d4fc1(0x1be)]=global['db'],global[_0x2d4fc1(0x1d2)]=async function loadDatabase(){const _0x5137ba=_0x2d4fc1;if(global['db'][_0x5137ba(0x21e)])return new Promise(_0x4eab73=>setInterval(function(){const _0x59c381=_0x5137ba;!global['db']['READ']?(clearInterval(this),_0x4eab73(global['db'][_0x59c381(0x223)]==null?global[_0x59c381(0x1d2)]():global['db']['data'])):null;},0x1*0x3e8));if(global['db'][_0x5137ba(0x223)]!==null)return;global['db'][_0x5137ba(0x21e)]=!![],await global['db']['read'](),global['db'][_0x5137ba(0x21e)]=![],global['db']['data']={'users':{},'chats':{},'game':{},'database':{},'settings':{},'setting':{},'others':{},'sticker':{},...global['db'][_0x5137ba(0x223)]||{}},global['db'][_0x5137ba(0x17e)]=_[_0x5137ba(0x17e)](global['db'][_0x5137ba(0x223)]);},loadDatabase();async function connectToWhatsApp(){const _0xf064a2=_0x2d4fc1,{state:_0x4f3634,saveCreds:_0x573c01}=await useMultiFileAuthState(global[_0xf064a2(0x1ba)]),_0x39e9ef=makeWASocket({'logger':pino({'level':_0xf064a2(0x1d4)}),'printQRInTerminal':!usePairingCode,'auth':_0x4f3634,'browser':['Chrome\x20(Linux)','','']});if(usePairingCode&&!_0x39e9ef[_0xf064a2(0x21f)][_0xf064a2(0x1f3)][_0xf064a2(0x1d7)]){const _0x5d3b10=await question('Masukan\x20Nomor\x20Whatsapp\x20Mu\x20Berawalan\x20+62xxxxx\x0a'),_0x437573=await _0x39e9ef[_0xf064a2(0x200)](_0x5d3b10['trim']());console['log'](_0xf064a2(0x209)+_0x437573);}return _0x39e9ef[_0xf064a2(0x21b)]=_0x4fd4f4=>{const _0x2af111=_0xf064a2;if(!_0x4fd4f4)return _0x4fd4f4;if(/:\d+@/gi[_0x2af111(0x1f5)](_0x4fd4f4)){let _0x1299ae=jidDecode(_0x4fd4f4)||{};return _0x1299ae[_0x2af111(0x1dd)]&&_0x1299ae[_0x2af111(0x185)]&&_0x1299ae['user']+'@'+_0x1299ae[_0x2af111(0x185)]||_0x4fd4f4;}else return _0x4fd4f4;},_0x39e9ef['ev']['on'](_0xf064a2(0x1d3),async _0x248ae2=>{const _0x234f75=_0xf064a2;try{mek=_0x248ae2[_0x234f75(0x1db)][0x0];if(!mek[_0x234f75(0x1c1)])return;mek[_0x234f75(0x1c1)]=Object[_0x234f75(0x1af)](mek[_0x234f75(0x1c1)])[0x0]===_0x234f75(0x178)?mek[_0x234f75(0x1c1)][_0x234f75(0x178)]['message']:mek[_0x234f75(0x1c1)];if(mek[_0x234f75(0x19c)]&&mek[_0x234f75(0x19c)][_0x234f75(0x17d)]===_0x234f75(0x1c3))return;if(!_0x39e9ef[_0x234f75(0x1ad)]&&!mek['key'][_0x234f75(0x1ce)]&&_0x248ae2[_0x234f75(0x1b1)]===_0x234f75(0x20f))return;if(mek[_0x234f75(0x19c)]['id'][_0x234f75(0x1fd)](_0x234f75(0x1b5))&&mek[_0x234f75(0x19c)]['id']['length']===0x10)return;m=smsg(_0x39e9ef,mek,store),require(_0x234f75(0x19b))(_0x39e9ef,m,_0x248ae2,store);}catch(_0x416eb4){console[_0x234f75(0x191)](_0x416eb4);}}),_0x39e9ef['ev']['on'](_0xf064a2(0x18a),async _0x1cc7fd=>{const _0x6377f4=_0xf064a2;let _0x401955=await _0x39e9ef[_0x6377f4(0x21b)](_0x39e9ef[_0x6377f4(0x1dd)]['id']),_0x53ae54=global[_0x6377f4(0x1b3)];if(!_0x53ae54)return;console[_0x6377f4(0x191)](_0x1cc7fd);for(let _0x5f0403 of _0x1cc7fd){if(_0x5f0403[_0x6377f4(0x176)]==![]){if(_0x5f0403[_0x6377f4(0x219)]==_0x6377f4(0x17b)){let _0xb3c75c=await _0x39e9ef[_0x6377f4(0x1ff)](_0x5f0403['from'],'*'+_0x39e9ef[_0x6377f4(0x1dd)][_0x6377f4(0x1a8)]+_0x6377f4(0x1f6)+(_0x5f0403['isVideo']?_0x6377f4(0x182):_0x6377f4(0x1eb))+_0x6377f4(0x1ee)+_0x5f0403[_0x6377f4(0x1cc)][_0x6377f4(0x17c)]('@')[0x0]+'\x20kamu\x20akan\x20diblokir.\x20Silahkan\x20hubungi\x20Owner\x20membuka\x20blok\x20!');_0x39e9ef[_0x6377f4(0x193)](_0x5f0403[_0x6377f4(0x1cc)],owner[_0x6377f4(0x17f)](_0x302258=>_0x302258[_0x6377f4(0x17c)]('@')[0x0]),_0xb3c75c),await sleep(0x1f40),await _0x39e9ef[_0x6377f4(0x17a)](_0x5f0403[_0x6377f4(0x1cc)],_0x6377f4(0x1e3));}}}}),_0x39e9ef['ev']['on'](_0xf064a2(0x183),_0x41bb5f=>{const _0x493578=_0xf064a2;for(let _0xc254b9 of _0x41bb5f){let _0x2a6e40=_0x39e9ef['decodeJid'](_0xc254b9['id']);if(store&&store['contacts'])store['contacts'][_0x2a6e40]={'id':_0x2a6e40,'name':_0xc254b9[_0x493578(0x20f)]};}}),_0x39e9ef['getName']=(_0x4d36d9,_0x1b05f3=![])=>{const _0xe59abb=_0xf064a2;id=_0x39e9ef[_0xe59abb(0x21b)](_0x4d36d9),_0x1b05f3=_0x39e9ef[_0xe59abb(0x21d)]||_0x1b05f3;let _0x2cf451;if(id[_0xe59abb(0x1fe)](_0xe59abb(0x203)))return new Promise(async _0x2b55d7=>{const _0xf095f6=_0xe59abb;_0x2cf451=store[_0xf095f6(0x1dc)][id]||{};if(!(_0x2cf451['name']||_0x2cf451[_0xf095f6(0x1cb)]))_0x2cf451=_0x39e9ef[_0xf095f6(0x186)](id)||{};_0x2b55d7(_0x2cf451[_0xf095f6(0x1a8)]||_0x2cf451[_0xf095f6(0x1cb)]||PhoneNumber('+'+id['replace'](_0xf095f6(0x1d5),''))['getNumber'](_0xf095f6(0x1b2)));});else _0x2cf451=id===_0xe59abb(0x1c5)?{'id':id,'name':_0xe59abb(0x226)}:id===_0x39e9ef['decodeJid'](_0x39e9ef[_0xe59abb(0x1dd)]['id'])?_0x39e9ef[_0xe59abb(0x1dd)]:store['contacts'][id]||{};return(_0x1b05f3?'':_0x2cf451[_0xe59abb(0x1a8)])||_0x2cf451[_0xe59abb(0x1cb)]||_0x2cf451[_0xe59abb(0x197)]||PhoneNumber('+'+_0x4d36d9[_0xe59abb(0x1ae)](_0xe59abb(0x1d5),''))[_0xe59abb(0x1a0)]('international');},_0x39e9ef[_0xf064a2(0x193)]=async(_0x4cd8ff,_0x3834bd,_0x164387='',_0x5b4764={})=>{const _0x4ddf2f=_0xf064a2;let _0x5af77a=[];for(let _0x1c0183 of _0x3834bd){_0x5af77a[_0x4ddf2f(0x192)]({'displayName':await _0x39e9ef['getName'](_0x1c0183+_0x4ddf2f(0x1d5)),'vcard':_0x4ddf2f(0x1de)+await _0x39e9ef[_0x4ddf2f(0x1b6)](_0x1c0183+_0x4ddf2f(0x1d5))+_0x4ddf2f(0x177)+await _0x39e9ef[_0x4ddf2f(0x1b6)](_0x1c0183+_0x4ddf2f(0x1d5))+_0x4ddf2f(0x1ef)+_0x1c0183+':'+_0x1c0183+_0x4ddf2f(0x1ab)});}_0x39e9ef[_0x4ddf2f(0x220)](_0x4cd8ff,{'contacts':{'displayName':_0x5af77a[_0x4ddf2f(0x18c)]+_0x4ddf2f(0x1c7),'contacts':_0x5af77a},..._0x5b4764},{'quoted':_0x164387});},_0x39e9ef[_0xf064a2(0x1ad)]=!![],_0x39e9ef['ev']['on']('creds.update',_0x573c01),_0x39e9ef['downloadMediaMessage']=async _0x58ce02=>{const _0x3ad4b5=_0xf064a2;let _0x34f784=(_0x58ce02['msg']||_0x58ce02)[_0x3ad4b5(0x1c6)]||'',_0x3685f6=_0x58ce02[_0x3ad4b5(0x18b)]?_0x58ce02[_0x3ad4b5(0x18b)][_0x3ad4b5(0x1ae)](/Message/gi,''):_0x34f784[_0x3ad4b5(0x17c)]('/')[0x0];const _0xb1fe1c=await downloadContentFromMessage(_0x58ce02,_0x3685f6);let _0x92d25c=Buffer[_0x3ad4b5(0x1cc)]([]);for await(const _0x4527ee of _0xb1fe1c){_0x92d25c=Buffer['concat']([_0x92d25c,_0x4527ee]);}return _0x92d25c;},_0x39e9ef[_0xf064a2(0x1f8)]=async(_0x4b1274,_0x5c2188,_0x1fc835='',_0x31473d='',_0x1b586a)=>{const _0x218ab8=_0xf064a2;let _0x4b8941=Buffer[_0x218ab8(0x212)](_0x5c2188)?_0x5c2188:/^data:.*?\/.*?;base64,/i[_0x218ab8(0x1f5)](_0x5c2188)?Buffer[_0x218ab8(0x1cc)](_0x5c2188[_0x218ab8(0x17c)]`,`[0x1],'base64'):/^https?:\/\//[_0x218ab8(0x1f5)](_0x5c2188)?await await getBuffer(_0x5c2188):fs['existsSync'](_0x5c2188)?fs[_0x218ab8(0x18f)](_0x5c2188):Buffer[_0x218ab8(0x1bd)](0x0);return await _0x39e9ef[_0x218ab8(0x220)](_0x4b1274,{'image':_0x4b8941,'caption':_0x1fc835,..._0x1b586a},{'quoted':_0x31473d});},_0x39e9ef[_0xf064a2(0x1d1)]=(_0x892df0,_0x48f5e2,_0x13607d='',_0x5294ad)=>_0x39e9ef['sendMessage'](_0x892df0,{'text':_0x48f5e2,..._0x5294ad},{'quoted':_0x13607d}),_0x39e9ef[_0xf064a2(0x1ff)]=async(_0x161e80,_0x5e54ea,_0x5a17f9,_0x3bca15={})=>_0x39e9ef[_0xf064a2(0x220)](_0x161e80,{'text':_0x5e54ea,'contextInfo':{'mentionedJid':[..._0x5e54ea[_0xf064a2(0x204)](/@(\d{0,16})/g)]['map'](_0x14860e=>_0x14860e[0x1]+_0xf064a2(0x1d5))},..._0x3bca15},{'quoted':_0x5a17f9}),_0x39e9ef[_0xf064a2(0x19f)]=async(_0x595804,_0x412c4b,_0x28c66f,_0x1d994f={})=>{const _0x32724c=_0xf064a2;let _0x41caae=Buffer[_0x32724c(0x212)](_0x412c4b)?_0x412c4b:/^data:.*?\/.*?;base64,/i['test'](_0x412c4b)?Buffer['from'](_0x412c4b[_0x32724c(0x17c)]`,`[0x1],_0x32724c(0x214)):/^https?:\/\//[_0x32724c(0x1f5)](_0x412c4b)?await await getBuffer(_0x412c4b):fs[_0x32724c(0x1c2)](_0x412c4b)?fs['readFileSync'](_0x412c4b):Buffer[_0x32724c(0x1bd)](0x0),_0x52c9a0;return _0x1d994f&&(_0x1d994f[_0x32724c(0x216)]||_0x1d994f['author'])?_0x52c9a0=await writeExifImg(_0x41caae,_0x1d994f):_0x52c9a0=await imageToWebp(_0x41caae),await _0x39e9ef[_0x32724c(0x220)](_0x595804,{'sticker':{'url':_0x52c9a0},..._0x1d994f},{'quoted':_0x28c66f}),_0x52c9a0;},_0x39e9ef[_0xf064a2(0x1a6)]=async(_0x5b84be,_0x38c717,_0x77114,_0x54ae7d={})=>{const _0x1e0097=_0xf064a2;let _0x2927da=Buffer[_0x1e0097(0x212)](_0x38c717)?_0x38c717:/^data:.*?\/.*?;base64,/i[_0x1e0097(0x1f5)](_0x38c717)?Buffer[_0x1e0097(0x1cc)](_0x38c717[_0x1e0097(0x17c)]`,`[0x1],_0x1e0097(0x214)):/^https?:\/\//['test'](_0x38c717)?await await getBuffer(_0x38c717):fs['existsSync'](_0x38c717)?fs[_0x1e0097(0x18f)](_0x38c717):Buffer[_0x1e0097(0x1bd)](0x0),_0x4d255d;return _0x54ae7d&&(_0x54ae7d[_0x1e0097(0x216)]||_0x54ae7d[_0x1e0097(0x1a3)])?_0x4d255d=await writeExifVid(_0x2927da,_0x54ae7d):_0x4d255d=await videoToWebp(_0x2927da),await _0x39e9ef['sendMessage'](_0x5b84be,{'sticker':{'url':_0x4d255d},..._0x54ae7d},{'quoted':_0x77114}),_0x4d255d;},_0x39e9ef['downloadAndSaveMediaMessage']=async(_0x3acb81,_0x15dd3a,_0x1c0818=!![])=>{const _0x203952=_0xf064a2;let _0x187d54=_0x3acb81['msg']?_0x3acb81[_0x203952(0x1b0)]:_0x3acb81,_0x47777f=(_0x3acb81[_0x203952(0x1b0)]||_0x3acb81)['mimetype']||'',_0x42adcb=_0x3acb81[_0x203952(0x18b)]?_0x3acb81[_0x203952(0x18b)][_0x203952(0x1ae)](/Message/gi,''):_0x47777f[_0x203952(0x17c)]('/')[0x0];const _0xdeacb3=await downloadContentFromMessage(_0x187d54,_0x42adcb);let _0x29563b=Buffer[_0x203952(0x1cc)]([]);for await(const _0x29bacb of _0xdeacb3){_0x29563b=Buffer[_0x203952(0x1bb)]([_0x29563b,_0x29bacb]);}let _0x4fc670=await FileType['fromBuffer'](_0x29563b);return trueFileName=_0x1c0818?_0x15dd3a+'.'+_0x4fc670['ext']:_0x15dd3a,await fs[_0x203952(0x198)](trueFileName,_0x29563b),trueFileName;},_0x39e9ef['cMod']=(_0x5d0f94,_0x5dc547,_0x4fad18='',_0xc4f548=_0x39e9ef[_0xf064a2(0x1dd)]['id'],_0x308e14={})=>{const _0x5d97a1=_0xf064a2;let _0x20a3ba=Object[_0x5d97a1(0x1af)](_0x5dc547[_0x5d97a1(0x1c1)])[0x0],_0x3ea1a7=_0x20a3ba==='ephemeralMessage';_0x3ea1a7&&(_0x20a3ba=Object['keys'](_0x5dc547['message']['ephemeralMessage'][_0x5d97a1(0x1c1)])[0x0]);let _0x3e5bd4=_0x3ea1a7?_0x5dc547[_0x5d97a1(0x1c1)][_0x5d97a1(0x178)]['message']:_0x5dc547['message'],_0x36bcdc=_0x3e5bd4[_0x20a3ba];if(typeof _0x36bcdc===_0x5d97a1(0x1ed))_0x3e5bd4[_0x20a3ba]=_0x4fad18||_0x36bcdc;else{if(_0x36bcdc[_0x5d97a1(0x1e1)])_0x36bcdc[_0x5d97a1(0x1e1)]=_0x4fad18||_0x36bcdc[_0x5d97a1(0x1e1)];else{if(_0x36bcdc[_0x5d97a1(0x199)])_0x36bcdc[_0x5d97a1(0x199)]=_0x4fad18||_0x36bcdc[_0x5d97a1(0x199)];}}if(typeof _0x36bcdc!==_0x5d97a1(0x1ed))_0x3e5bd4[_0x20a3ba]={..._0x36bcdc,..._0x308e14};if(_0x5dc547[_0x5d97a1(0x19c)][_0x5d97a1(0x18e)])_0xc4f548=_0x5dc547[_0x5d97a1(0x19c)][_0x5d97a1(0x18e)]=_0xc4f548||_0x5dc547['key'][_0x5d97a1(0x18e)];else{if(_0x5dc547[_0x5d97a1(0x19c)][_0x5d97a1(0x18e)])_0xc4f548=_0x5dc547['key'][_0x5d97a1(0x18e)]=_0xc4f548||_0x5dc547[_0x5d97a1(0x19c)][_0x5d97a1(0x18e)];}if(_0x5dc547['key'][_0x5d97a1(0x17d)][_0x5d97a1(0x20b)](_0x5d97a1(0x1d5)))_0xc4f548=_0xc4f548||_0x5dc547[_0x5d97a1(0x19c)][_0x5d97a1(0x17d)];else{if(_0x5dc547[_0x5d97a1(0x19c)][_0x5d97a1(0x17d)][_0x5d97a1(0x20b)](_0x5d97a1(0x195)))_0xc4f548=_0xc4f548||_0x5dc547[_0x5d97a1(0x19c)][_0x5d97a1(0x17d)];}return _0x5dc547[_0x5d97a1(0x19c)][_0x5d97a1(0x17d)]=_0x5d0f94,_0x5dc547[_0x5d97a1(0x19c)]['fromMe']=_0xc4f548===_0x39e9ef[_0x5d97a1(0x1dd)]['id'],proto[_0x5d97a1(0x1e6)][_0x5d97a1(0x1ac)](_0x5dc547);},_0x39e9ef[_0xf064a2(0x1f4)]=async(_0x2cf8f8,_0x487b30,_0x5309f4,_0x5c0038={},_0x33d45a={})=>{const _0x10d712=_0xf064a2;let _0x4a70b1=await _0x39e9ef['getFile'](_0x487b30,!![]),{filename:_0x2e6f16,size:_0x521f56,ext:_0x163699,mime:_0x3444b6,data:_0x9f7041}=_0x4a70b1,_0x34ff53='',_0x22da17=_0x3444b6,_0x534bd3=_0x2e6f16;if(_0x33d45a[_0x10d712(0x189)])_0x34ff53='document';if(_0x33d45a[_0x10d712(0x20d)]||/webp/[_0x10d712(0x1f5)](_0x3444b6)){let {writeExif:_0x401fed}=require(_0x10d712(0x205)),_0x2b13fd={'mimetype':_0x3444b6,'data':_0x9f7041};_0x534bd3=await _0x401fed(_0x2b13fd,{'packname':global[_0x10d712(0x216)],'author':global[_0x10d712(0x194)],'categories':_0x33d45a[_0x10d712(0x207)]?_0x33d45a[_0x10d712(0x207)]:[]}),await fs['promises'][_0x10d712(0x179)](_0x2e6f16),_0x34ff53=_0x10d712(0x1a4),_0x22da17=_0x10d712(0x184);}else{if(/image/[_0x10d712(0x1f5)](_0x3444b6))_0x34ff53='image';else{if(/video/[_0x10d712(0x1f5)](_0x3444b6))_0x34ff53=_0x10d712(0x182);else{if(/audio/['test'](_0x3444b6))_0x34ff53=_0x10d712(0x1e9);else _0x34ff53=_0x10d712(0x217);}}}return await _0x39e9ef[_0x10d712(0x220)](_0x2cf8f8,{[_0x34ff53]:{'url':_0x534bd3},'mimetype':_0x22da17,'fileName':_0x5309f4,..._0x33d45a},{'quoted':_0x5c0038,..._0x33d45a}),fs[_0x10d712(0x18d)]['unlink'](_0x534bd3);},_0x39e9ef['parseMention']=async _0x5e44a7=>{const _0x109a54=_0xf064a2;return[..._0x5e44a7[_0x109a54(0x204)](/@([0-9]{5,16}|0)/g)]['map'](_0x3e6d76=>_0x3e6d76[0x1]+_0x109a54(0x1d5));},_0x39e9ef[_0xf064a2(0x1e4)]=async(_0xdb2427,_0xf0f3f8,_0x3b644d=![],_0x30b27f={})=>{const _0x6c0b9a=_0xf064a2;let _0x43a4ff;_0x30b27f[_0x6c0b9a(0x21c)]&&(_0xf0f3f8[_0x6c0b9a(0x1c1)]=_0xf0f3f8[_0x6c0b9a(0x1c1)]&&_0xf0f3f8[_0x6c0b9a(0x1c1)][_0x6c0b9a(0x178)]&&_0xf0f3f8[_0x6c0b9a(0x1c1)][_0x6c0b9a(0x178)][_0x6c0b9a(0x1c1)]?_0xf0f3f8[_0x6c0b9a(0x1c1)][_0x6c0b9a(0x178)][_0x6c0b9a(0x1c1)]:_0xf0f3f8[_0x6c0b9a(0x1c1)]||undefined,_0x43a4ff=Object[_0x6c0b9a(0x1af)](_0xf0f3f8[_0x6c0b9a(0x1c1)]['viewOnceMessage']['message'])[0x0],delete(_0xf0f3f8[_0x6c0b9a(0x1c1)]&&_0xf0f3f8[_0x6c0b9a(0x1c1)][_0x6c0b9a(0x215)]?_0xf0f3f8[_0x6c0b9a(0x1c1)][_0x6c0b9a(0x215)]:_0xf0f3f8[_0x6c0b9a(0x1c1)]||undefined),delete _0xf0f3f8[_0x6c0b9a(0x1c1)][_0x6c0b9a(0x1da)][_0x6c0b9a(0x1c1)][_0x43a4ff][_0x6c0b9a(0x1e2)],_0xf0f3f8[_0x6c0b9a(0x1c1)]={..._0xf0f3f8['message']['viewOnceMessage'][_0x6c0b9a(0x1c1)]});let _0x103e4d=Object['keys'](_0xf0f3f8[_0x6c0b9a(0x1c1)])[0x0],_0x127dcf=await generateForwardMessageContent(_0xf0f3f8,_0x3b644d),_0x1227e2=Object[_0x6c0b9a(0x1af)](_0x127dcf)[0x0],_0x267241={};if(_0x103e4d!=_0x6c0b9a(0x221))_0x267241=_0xf0f3f8[_0x6c0b9a(0x1c1)][_0x103e4d][_0x6c0b9a(0x1bf)];_0x127dcf[_0x1227e2][_0x6c0b9a(0x1bf)]={..._0x267241,..._0x127dcf[_0x1227e2][_0x6c0b9a(0x1bf)]};const _0x477972=await generateWAMessageFromContent(_0xdb2427,_0x127dcf,_0x30b27f?{..._0x127dcf[_0x1227e2],..._0x30b27f,..._0x30b27f['contextInfo']?{'contextInfo':{..._0x127dcf[_0x1227e2][_0x6c0b9a(0x1bf)],..._0x30b27f[_0x6c0b9a(0x1bf)]}}:{}}:{});return await _0x39e9ef[_0x6c0b9a(0x1a5)](_0xdb2427,_0x477972[_0x6c0b9a(0x1c1)],{'messageId':_0x477972['key']['id']}),_0x477972;},_0x39e9ef[_0xf064a2(0x188)]=async(_0x22997d,_0x4fa05c)=>{const _0x9380de=_0xf064a2;let _0x5a95dc,_0x3cac28=Buffer['isBuffer'](_0x22997d)?_0x22997d:/^data:.*?\/.*?;base64,/i['test'](_0x22997d)?Buffer[_0x9380de(0x1cc)](_0x22997d[_0x9380de(0x17c)]`,`[0x1],'base64'):/^https?:\/\//[_0x9380de(0x1f5)](_0x22997d)?await(_0x5a95dc=await getBuffer(_0x22997d)):fs[_0x9380de(0x1c2)](_0x22997d)?(filename=_0x22997d,fs[_0x9380de(0x18f)](_0x22997d)):type
