### ISSUE TITLE
CSV parser

### ISSUE THREAD

**Issue by norecord** [MasterDevX/XCoder#13]
I have done a parser of .csv configuration format on C# :)
[link](https://github.com/norecord/csv_parser)

**Comment by FourCinnamon0** [comment]
Why did you put this in an issue on XCoder?

**Comment by norecord** [comment]
@FourCinnamon0 Maybe someone will need it

**Comment by FourCinnamon0** [comment]
But why is this an __issue__ on XCoder?
I get that someone might need it but you can't just make issues on random repos for advertising
