### ISSUE TITLE
Error during the installation

### ISSUE THREAD

**Issue by dinamitebla** [MasterDevX/XCoder#15]
hi, while I was installing the program to decompress the clash of clans files the program gave this error, do you know how to fix?
thanks for any help

[2020-05-01 16-34-02.zip](https://github.com/MasterDevX/XCoder/files/4564727/2020-05-01.16-34-02.zip)

**Comment by LouayTech** [comment]
Check if your python version is 3,5 or higher. Open cmd typ Pyhton --version

**Comment by fourk0** [comment]
There is no clash of clans support
