### ISSUE TITLE
Decoding .scw files?

### ISSUE THREAD

**Issue by yildiz** [MasterDevX/XCoder#2]
Hi, first things first thank you for this repo, it helped me a lot.

I wonder how can I see how the characters' look like. Is there any way to do that?

I think these are the files of the characters' look.

**Comment by MasterDevX** [comment]
Hello, glad to hear this project was useful for you!
You are right, *.scw files are compressed models of the characters, but it is impossible to decompress them using XCoder. Currently I don't know how to decompress them.
