### ISSUE TITLE
Can't compress lzham compression

### ISSUE THREAD

**Issue by hacker9905** [MasterDevX/XCoder#20]
Can't compress LZHAM compression

**Comment by spiky-s** [comment]
what error? what does it write to the console, what does it write to the log?

**Comment by hacker9905** [comment]
![Screenshot_2020-09-17-23-22-15-512_ru iiec pydroid3](https://user-images.githubusercontent.com/71434073/93508950-adf3a000-f93c-11ea-8a60-bc82c55f0d44.jpg)
And the log.txt file is empty 
![PicsArt_09-17-11 27 25](https://user-images.githubusercontent.com/71434073/93509494-70dbdd80-f93d-11ea-84b8-b25a8db871a3.jpg)
 @spiky-s

**Comment by spiky-s** [comment]
try to open issue on the lzham repository page: https://github.com/Galaxy1036/pylzham
xcoder uses this library, and in this case it causes the error

**Comment by spiky-s** [comment]
Although ... It even became interesting to myself, I'll go figure it out too)

**Comment by hacker9905** [comment]
Ok

**Comment by spiky-s** [comment]
I wrote to the author of the library, saying that you can try to reinstall the library somehow, or use only lzma for compression. And since all games support lzma and lzham, most likely I will use the 2nd option

**Comment by hacker9905** [comment]
Then, It won't be possible to compress with LZHAM?☹️

**Comment by spiky-s** [comment]
Once it was possible, now something seems to be broken. In general, I'll see how it turns out, clash of clans supports lzma too

**Comment by hacker9905** [comment]
Ok, I am looking forward to you for finding a solution ☺

**Comment by hacker9905** [comment]
Update! It got fixed after I re-installed Lzham @spiky-s 😄
