### ISSUE TITLE
Can't compress/Decompress Clash of Clans old version Sc files

### ISSUE THREAD

**Issue by hacker9905** [MasterDevX/XCoder#21]
I can't compress/decompress Clash of clans old version Sc files with the tool☹️☹️
![Screenshot_2020-09-21-15-52-46-581_com gmail heagoo apkeditor pro](https://user-images.githubusercontent.com/71434073/93756523-dcb29480-fc22-11ea-8aaf-0916181253e8.png)

**Comment by spiky-s** [comment]
This isn't implemented, because old sc files have another structure. But if it is necessary, then in the next updates I will try to add it
